# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache Software License 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0, or the MIT license
# which is available at https://opensource.org/licenses/MIT.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

package(default_visibility = ["//visibility:public"])

load("@rules_cc//cc:defs.bzl", "cc_library")
load("@rules_rust//cargo:defs.bzl", "cargo_build_script", "cargo_toml_env_vars")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test_suite")

cargo_toml_env_vars(
    name = "cargo_toml_env_vars",
    src = "Cargo.toml",
)

filegroup(
    name = "all_srcs",
    srcs = glob(["**"]),
)

# Generate the binding lib
cc_library(
    name = "iceoryx2-pal-posix-c-lib",
    srcs = [
        "src/c/socket_macros.c",
    ],
    hdrs = glob(["src/c/**"]),
    strip_include_prefix = "src/c",
    linkstatic = True,
    visibility = ["//visibility:public"],
)

cargo_build_script(
    name = "_bs",
    compile_data = glob(
        allow_empty = True,
        include = ["**"],
        exclude = [
            "**/* *",
            "**/*.rs",
            ".tmp_git_root/**/*",
            "BUILD",
            "BUILD.bazel",
            "WORKSPACE",
            "WORKSPACE.bazel",
        ],
    ),
    crate_name = "build_script_build",
    crate_root = "build.rs",
    data = glob(
        allow_empty = True,
        include = ["**"],
        exclude = [
            "**/* *",
            ".tmp_git_root/**/*",
            "BUILD",
            "BUILD.bazel",
            "WORKSPACE",
            "WORKSPACE.bazel",
        ],
    ),
    deps = [
        "@crate_index//:bindgen",
        "@crate_index//:cc",
    ],
    edition = "2021",
    pkg_name = "iceoryx2-pal-posix",
    rustc_env_files = [
        ":cargo_toml_env_vars",
    ],
    rustc_flags = [
        "--cap-lints=allow",
    ],
    srcs = glob(
        allow_empty = True,
        include = ["**/*.rs"],
    ),
    tags = [
        "cargo-bazel",
        "crate-name=iceoryx2-pal-posix",
        "manual",
        "noclippy",
        "norustfmt",
    ],
    version = "0.7.0",
    visibility = ["//visibility:private"],
)

alias(
    name = "build_script_build",
    actual = ":_bs",
    tags = ["manual"],
)

# Create the actual crate
rust_library(
    name = "iceoryx2-pal-posix",
    srcs = glob(["src/**/*.rs"]),
    compile_data = glob(
        allow_empty = True,
        include = ["**"],
        exclude = [
            "**/* *",
            ".tmp_git_root/**/*",
            "BUILD",
            "BUILD.bazel",
            "WORKSPACE",
            "WORKSPACE.bazel",
        ],
    ),
    deps = [
        "//iceoryx2-pal/concurrency-sync:iceoryx2-pal-concurrency-sync",
        "//iceoryx2-pal/configuration:iceoryx2-pal-configuration",
        "@crate_index//:lazy_static",
        ":iceoryx2-pal-posix-c-lib",
        ":build_script_build",
    ],
    rustc_env = {
        # - 'lib.rs' expects the location at 'env!("OUT_DIR")/posix_generated.rs'
        # - 'OUT_DIR' is set by 'bazel_bindgen_workaround' and points to the same
        #   folder where 'posix_generated.rs' is preset
        # - therefore the path needs to be corrected
        "BAZEL_BINDGEN_PATH_CORRECTION": "/.."
    },
    crate_features = select({
        "//:custom_pal_posix_enabled": ["custom_pal_posix"],
        "//conditions:default": [""],
    }),
)

rust_test_suite(
    name = "iceoryx2-pal-posix-tests",
    srcs = glob(["tests/**/*.rs"]),
    deps = [
        ":iceoryx2-pal-posix",
        "//iceoryx2-pal/testing:iceoryx2-pal-testing",
    ],
    proc_macro_deps = [
        "@crate_index//:generic-tests",
    ],
)
